package com.zhl.springboot.drools;

import com.zhl.springboot.drools.entity.Message;
import java.util.concurrent.atomic.AtomicInteger;

global String temp;
global AtomicInteger count;

//函数示例
function void print(String messgae){
    System.out.println(messgae);
}

//规则1
rule "say-hi"
    when
        $message: Message("hi".equals(messageType) && target!=null)
    then
        print("hi," + $message.getTarget() + ", welcome to drools\n");
    end